package utils;

public class musteribilgileri {
    /*
    [
    {
        "id": 126294,
        "firstName": "Deneme",
        "lastName": "Last",
        "middleInitial": "M",
        "email": "ma34@gmail.com",
        "mobilePhoneNumber": null,
        "phoneNumber": "123-123-3434",
        "zipCode": null,
        "address": "NYC",
        "city": null,
        "ssn": "123-34-3434",
        "createDate": null,
        "zelleEnrolled": null,
        "country": null,
        "state": null,
        "user": null,
        "accounts": null
    },
    {
        "id": 114351,
        "firstName": "Della",
        "lastName": "Heaney",
        "middleInitial": "Russell Homenick V",
        "email": "ricardo.larkin@yahoo.com",
        "mobilePhoneNumber": "123-456-7893",
        "phoneNumber": "213-456-7893",
        "zipCode": "53081",
        "address": "75164 McClure Stream",
        "city": "Gislasonburgh",
        "ssn": "823-25-7239",
        "createDate": "2021-12-05T23:00:00Z",
        "zelleEnrolled": true,
        "country": {
            "id": 3,
            "name": "USA",
            "states": null
        },
        "state": "New York43",
        "user": null,
        "accounts": null
    },
    {
        "id": 110452,
        "firstName": "Jasmine",
        "lastName": "Stehr",
        "middleInitial": "V",
        "email": "marni.zboncak@yahoo.com",
        "mobilePhoneNumber": "463-609-2097",
        "phoneNumber": "1-112-497-0270",
        "zipCode": "16525",
        "address": "14387 Al Ridge5343 Bert Burgs",
        "city": "Waltermouth",
        "ssn": "761-59-2911",
        "createDate": "2021-11-28T21:00:00Z",
        "zelleEnrolled": false,
        "country": {
            "id": 3,
            "name": "USA",
            "states": null
        },
        "state": "California",
        "user": {
            "id": 110016,
            "login": "leopoldo.reinger",
            "firstName": "Jasmine",
            "lastName": "Stehr",
            "email": "marni.zboncak@yahoo.com",
            "activated": true,
            "langKey": "en",
            "imageUrl": null,
            "resetDate": null
        },
        "accounts": null
    },
    {
        "id": 42697,
        "firstName": "Ali",
        "lastName": "Deckow",
        "middleInitial": "Leroy Hoeger Sipes",
        "email": "com.github.javafaker.Name@7c011174@gmail.com",
        "mobilePhoneNumber": "115-471-7051",
        "phoneNumber": "876-394-6968",
        "zipCode": "67321",
        "address": "I live in St louis MO",
        "city": "St Louis",
        "ssn": "473-22-1798",
        "createDate": "0211-09-09T05:50:36Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 85657,
        "firstName": "Demo",
        "lastName": "Team30",
        "middleInitial": "The",
        "email": "demot36@gmail.com",
        "mobilePhoneNumber": "532-156-3624",
        "phoneNumber": "532-156-3624",
        "zipCode": "06300",
        "address": "New York",
        "city": "New York",
        "ssn": "159-63-9248",
        "createDate": "2021-03-02T21:00:00Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": {
            "id": 85376,
            "login": "dt36",
            "firstName": "Demo",
            "lastName": "Team30",
            "email": "demot36@gmail.com",
            "activated": true,
            "langKey": "en",
            "imageUrl": null,
            "resetDate": null
        },
        "accounts": null
    },
    {
        "id": 75047,
        "firstName": "Maria",
        "lastName": "Maria",
        "middleInitial": "M",
        "email": "customer55@gmail.com",
        "mobilePhoneNumber": "123-456-7890",
        "phoneNumber": "123-456-7896",
        "zipCode": "0300",
        "address": "free world street",
        "city": "Sacramento",
        "ssn": "027-31-2727",
        "createDate": "2021-02-21T21:00:00Z",
        "zelleEnrolled": false,
        "country": {
            "id": 3,
            "name": "USA",
            "states": null
        },
        "state": "California",
        "user": {
            "id": 75194,
            "login": "customer55",
            "firstName": "Maria",
            "lastName": "Clark",
            "email": "customer55@gmail.com",
            "activated": true,
            "langKey": "en",
            "imageUrl": null,
            "resetDate": null
        },
        "accounts": null
    },
    {
        "id": 50865,
        "firstName": "Jacqueline",
        "lastName": "Emmerich",
        "middleInitial": "O",
        "email": "christopher.zulauf@example.com",
        "mobilePhoneNumber": "206-969-1243",
        "phoneNumber": "165-048-3654",
        "zipCode": "75632",
        "address": "Apt. 461 644 Hyatt Lane, Schowalterborough, KS 67042-7080",
        "city": "Jeanberg",
        "ssn": "355-88-2318",
        "createDate": "2019-12-13T10:20:00Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 50866,
        "firstName": "Wendell",
        "lastName": "Trantow",
        "middleInitial": "T",
        "email": "hugo.schneider@example.com",
        "mobilePhoneNumber": "047-152-6952",
        "phoneNumber": "542-396-7766",
        "zipCode": "63622-1699",
        "address": "Apt. 391 572 Rodrick Mountains, Port Myungfurt, KY 22925-3615",
        "city": "Greenholttown",
        "ssn": "821-84-3971",
        "createDate": "2020-12-13T10:20:00Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 43703,
        "firstName": "Alda",
        "lastName": "Monahan",
        "middleInitial": "Nichelle Hermann Kohler",
        "email": "com.github.javafaker.Name@7c011174@gmail.com",
        "mobilePhoneNumber": "909-162-8114",
        "phoneNumber": "231-501-9849",
        "zipCode": "67321",
        "address": "I live in St louis MO",
        "city": "St Louis",
        "ssn": "108-53-6655",
        "createDate": "0211-09-09T05:50:36Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 43707,
        "firstName": "Ariel",
        "lastName": "Lockman",
        "middleInitial": "Kyla Jacobson Leannon I",
        "email": "com.github.javafaker.Name@7c011174@gmail.com",
        "mobilePhoneNumber": "539-783-3603",
        "phoneNumber": "277-718-1185",
        "zipCode": "67321",
        "address": "I live in St louis MO",
        "city": "St Louis",
        "ssn": "224-71-4004",
        "createDate": "0211-09-09T05:50:36Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 59511,
        "firstName": "ismail",
        "lastName": "özk",
        "middleInitial": "a",
        "email": "ismailoezkan93@gmail.com",
        "mobilePhoneNumber": "111-111-1115",
        "phoneNumber": "123-456-7891",
        "zipCode": "16",
        "address": "schweiz",
        "city": "adana",
        "ssn": "398-56-4356",
        "createDate": "2020-10-20T22:00:00Z",
        "zelleEnrolled": true,
        "country": null,
        "state": "",
        "user": {
            "id": 58645,
            "login": "ismail16",
            "firstName": "LadyGaga",
            "lastName": "TeamTryCatch",
            "email": "ismailoezkan93@gmail.com",
            "activated": true,
            "langKey": "en",
            "imageUrl": null,
            "resetDate": null
        },
        "accounts": null
    },
    {
        "id": 43712,
        "firstName": "Everette",
        "lastName": "Dietrich",
        "middleInitial": "Paul Leffler Hirthe",
        "email": "com.github.javafaker.Name@7c011174@gmail.com",
        "mobilePhoneNumber": "853-190-1383",
        "phoneNumber": "145-502-8220",
        "zipCode": "67321",
        "address": "I live in St louis MO",
        "city": "St Louis",
        "ssn": "498-53-5576",
        "createDate": "0211-09-09T05:50:36Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 42665,
        "firstName": "US11",
        "lastName": "Team13",
        "middleInitial": "m",
        "email": "bg@gmail.com",
        "mobilePhoneNumber": "123-322-1234",
        "phoneNumber": "123-123-4567",
        "zipCode": "NewCity",
        "address": "sdf",
        "city": "NewCity",
        "ssn": "458-62-6584",
        "createDate": "2020-12-10T23:00:00Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": {
            "id": 41437,
            "login": "adf",
            "firstName": "LadyGaga",
            "lastName": "TeamTryCatch",
            "email": "as@sdf.com",
            "activated": true,
            "langKey": "en",
            "imageUrl": null,
            "resetDate": null
        },
        "accounts": null
    },
    {
        "id": 59532,
        "firstName": "myCustomer1",
        "lastName": "Williamson",
        "middleInitial": "Davina Russel Pollich",
        "email": "Name1@gmail.com",
        "mobilePhoneNumber": "548-779-7096",
        "phoneNumber": "264-723-4959",
        "zipCode": "67321",
        "address": "I live in St louis MO",
        "city": "St Louis",
        "ssn": "570-65-6993",
        "createDate": "0211-09-09T05:50:36Z",
        "zelleEnrolled": false,
        "country": null,
        "state": "",
        "user": null,
        "accounts": null
    },
    {
        "id": 93391,
        "firstName": "Team",
        "lastName": "Fifty Five",
        "middleInitial": "F",
        "email": "team54@gmail.com",
        "mobilePhoneNumber": "086-377-3814",
        "phoneNumber": "252-446-5912",
        "zipCode": "73710",
        "address": "32564 Willms Bypass",
        "city": "Fionaside",
        "ssn": "126-34-7860",
        "createDate": null,
        "zelleEnrolled": false,
        "country": null,
        "state": null,
        "user": null,
        "accounts": null
    },
    {
        "id": 75016,
        "firstName": "Maria",
        "lastName": "Maria",
        "middleInitial": "M",
        "email": "maria3@gmail.com",
        "mobilePhoneNumber": "123-456-7891",
        "phoneNumber": "123-456-7896",
        "zipCode": "0100",
        "address": "freedom street3",
        "city": "Austin3",
        "ssn": "222-33-5555",
        "createDate": "2021-02-19T21:00:00Z",
        "zelleEnrolled": true,
        "country": {
            "id": 3,
            "name": "USA",
            "states": null
        },
        "state": "Texas3",
        "user": null,
        "accounts": null
    },
    {
        "id": 85694,
        "firstName": "Winona",
        "lastName": "Abernathy",
        "middleInitial": "S",
        "email": "winonaabernathy@gmail.com",
        "mobilePhoneNumber": "222-230-1890",
        "phoneNumber": "271-169-8836",
        "zipCode": "09848-7861",
        "address": "1956 Hackett Mission",
        "city": "Fairfax",
        "ssn": "779-99-4600",
        "createDate": "2021-03-03T06:00:00Z",
        "zelleEnrolled": false,
        "country": {
            "id": 3,
            "name": "USA",
            "states": null
        },
        "state": "Virginia",
        "user": {
            "id": 86453,
            "login": "dino.kohler",
            "firstName": "Winona",
            "lastName": "Abernathy",
            "email": "winonaabernathy@gmail.com",
            "activated": true,
            "langKey": "en",
            "imageUrl": null,
            "resetDate": null
        },
        "accounts": null
    },
    {
        "id": 60997,
        "firstName": "Merrill",
        "lastName": "Price",
        "middleInitial": "J",
        "email": "MerrillPrice@gmail.com",
        "mobilePhoneNumber": "541-268-3662",
        "phoneNumber": "123-033-4202",
        "zipCode": "76253",
        "address": "451 Lang Mountain",
        "city": "New Paulmouth",
        "ssn": "531-95-8437",
        "createDate": null,
        "zelleEnrolled": false,
        "country": null,
        "state": null,
        "user": null,
        "accounts": null
    },
    {
        "id": 61032,
        "firstName": "Lesley",
        "lastName": "King",
        "middleInitial": "K",
        "email": "LesleyKing@gmail.com",
        "mobilePhoneNumber": "086-377-3814",
        "phoneNumber": "252-446-5912",
        "zipCode": "73710",
        "address": "32564 Willms Bypass",
        "city": "Fionaside",
        "ssn": "049-43-2360",
        "createDate": null,
        "zelleEnrolled": false,
        "country": null,
        "state": null,
        "user": null,
        "accounts": null
    },
    {
        "id": 61033,
        "firstName": "Ricardo",
        "lastName": "Mraz",
        "middleInitial": "K",
        "email": "RicardoMraz@gmail.com",
        "mobilePhoneNumber": "468-534-3127",
        "phoneNumber": "496-514-2808",
        "zipCode": "02316",
        "address": "33977 Jerrold Underpass",
        "city": "New Justin",
        "ssn": "612-28-5133",
        "createDate": null,
        "zelleEnrolled": true,
        "country": null,
        "state": null,
        "user": null,
        "accounts": null
    }
]
     */
}
